name: Build Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Test End-to-End
        run: npm run e2e:headless

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-video
          path: cypress/videos
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: 54.172.175.18
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Optional: If you need to execute specific commands on the server
          script: |
            echo "Connected to the server via SSH"
            # Add your desired commands here
            # Example: npm run build
            cd test-cicd &&\
            git pull &&\
            npm install &&\
            npm run build &&\
            pm2 restart all
