name: Build Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Test End-to-End
        run: npm run e2e:headless

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-video
          path: cypress/videos

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build docker image with ghcr
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/thomasdelecluse/test-cicd:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: 34.224.66.44
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Optional: If you need to execute specific commands on the server
          script: |
            echo "Connected to the server via SSH"
            # Add your desired commands here
            # Example: npm run build
            
            docker login ghcr.io -u thomasdelecluse -p ${{ secrets.TOKEN }}
            docker stop test-cicd 
            docker rm test-cicd
            docker pull ghcr.io/thomasdelecluse/test-cicd:latest
            docker run -d --name test-cicd -p 3001:3000 ghcr.io/thomasdelecluse/test-cicd:latest
            docker run --name mariadbdatabase -e MYSQL_ROOT_PASSWORD=pass -p 3306:3306 -d mariadb:latest
